server:
  port: 8888

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        tags: user.name=user, user.password=password
      host: registry
      port: 8500
    config:
      server:
        native:
          search-locations: /Users/wangwei/code/GitHub/spring-boot-cloud/config-repo
  rabbitmq:
    host: rabbitmq
  profiles:
    active: native

security:
  user:
    name: user
    password: password
