server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        native:
          search-locations: /Users/wangwei/code/GitHub/spring-boot-cloud/config-repo
  rabbitmq:
    host: rabbitmq
  profiles:
    active: native

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
