server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  cloud:
    consul:
      discovery:
        health-check-path: ${server.context-path}${management.context-path}/health
        tags: management.context-path=${server.context-path}${management.context-path}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth-service?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    show-sql: true
